package keyboard

type Finger int

const (
	Pinky Finger = iota
	Ring
	Middle
	Index
	Thumb
	Any
)

type key struct {
	label     string
	width     int
	finger    Finger
	gap       bool
	rightless bool
	leftless  bool
	divLabel  string
	evCode    uint16
}

var sizes = map[int][][]key{
	60:  size60,
	65:  size65,
	75:  size75,
	80:  size80,
	96:  size96,
	100: size100,
}

var size60 = [][]key{
	{
		{label: "Esc", width: 3, finger: Pinky, evCode: 1},
		{label: "1", width: 3, finger: Pinky, evCode: 2},
		{label: "2", width: 3, finger: Ring, evCode: 3},
		{label: "3", width: 3, finger: Middle, evCode: 4},
		{label: "4", width: 3, finger: Index, evCode: 5},
		{label: "5", width: 3, finger: Index, evCode: 6},
		{label: "6", width: 3, finger: Index, evCode: 7},
		{label: "7", width: 3, finger: Index, evCode: 8},
		{label: "8", width: 3, finger: Middle, evCode: 9},
		{label: "9", width: 3, finger: Ring, evCode: 10},
		{label: "0", width: 3, finger: Pinky, evCode: 11},
		{label: "-", width: 3, finger: Pinky, evCode: 12},
		{label: "=", width: 3, finger: Pinky, evCode: 13},
		{label: "<--", width: 8, finger: Pinky, evCode: 14},
	},
	{
		{label: "Tab⇄", width: 6, finger: Pinky, evCode: 15},
		{label: "Q", width: 3, finger: Pinky, evCode: 16},
		{label: "W", width: 3, finger: Ring, evCode: 17},
		{label: "E", width: 3, finger: Middle, evCode: 18},
		{label: "R", width: 3, finger: Index, evCode: 19},
		{label: "T", width: 3, finger: Index, evCode: 20},
		{label: "Y", width: 3, finger: Index, evCode: 21},
		{label: "U", width: 3, finger: Index, evCode: 22},
		{label: "I", width: 3, finger: Middle, evCode: 23},
		{label: "O", width: 3, finger: Ring, evCode: 24},
		{label: "P", width: 3, finger: Pinky, evCode: 25},
		{label: "[", width: 3, finger: Pinky, evCode: 26},
		{label: "]", width: 3, finger: Pinky, evCode: 27},
		{label: "\\", width: 5, finger: Pinky, evCode: 43},
	},
	{
		{label: "Caps", width: 6, finger: Pinky, evCode: 58},
		{label: "A", width: 3, finger: Pinky, evCode: 30},
		{label: "S", width: 3, finger: Ring, evCode: 31},
		{label: "D", width: 3, finger: Middle, evCode: 32},
		{label: "F", width: 3, finger: Index, evCode: 33},
		{label: "G", width: 3, finger: Index, evCode: 34},
		{label: "H", width: 3, finger: Index, evCode: 35},
		{label: "J", width: 3, finger: Index, evCode: 36},
		{label: "K", width: 3, finger: Middle, evCode: 37},
		{label: "L", width: 3, finger: Ring, evCode: 38},
		{label: ";", width: 3, finger: Pinky, evCode: 39},
		{label: "'", width: 3, finger: Pinky, evCode: 40},
		{label: "Enter↵", width: 9, finger: Pinky, evCode: 28},
	},
	{
		{label: "Shift", width: 10, finger: Pinky, evCode: 42},
		{label: "Z", width: 3, finger: Pinky, evCode: 44},
		{label: "X", width: 3, finger: Ring, evCode: 45},
		{label: "C", width: 3, finger: Middle, evCode: 46},
		{label: "V", width: 3, finger: Index, evCode: 47},
		{label: "B", width: 3, finger: Index, evCode: 48},
		{label: "N", width: 3, finger: Index, evCode: 49},
		{label: "M", width: 3, finger: Index, evCode: 50},
		{label: ",", width: 3, finger: Middle, evCode: 51},
		{label: ".", width: 3, finger: Ring, evCode: 52},
		{label: "/", width: 3, finger: Pinky, evCode: 53},
		{label: "Shift", width: 9, finger: Pinky, evCode: 54},
	},
	{
		{label: "Ctrl", width: 6, finger: Pinky, evCode: 29},
		{label: "⌘", width: 3, finger: Ring, evCode: 125},
		{label: "Alt", width: 5, finger: Thumb, evCode: 56},
		{label: "Space", width: 22, finger: Thumb, evCode: 57},
		{label: "Alt", width: 5, finger: Thumb, evCode: 100},
		{label: "⌘", width: 3, finger: Ring, evCode: 126},
		{label: "Fn", width: 3, finger: Ring, evCode: 127},
		{label: "Ctrl", width: 6, finger: Pinky, evCode: 97},
	},
}

var size65 = [][]key{
	{
		{label: "Esc", width: 3, finger: Pinky, evCode: 1},
		{label: "1", width: 3, finger: Pinky, evCode: 2},
		{label: "2", width: 3, finger: Ring, evCode: 3},
		{label: "3", width: 3, finger: Middle, evCode: 4},
		{label: "4", width: 3, finger: Index, evCode: 5},
		{label: "5", width: 3, finger: Index, evCode: 6},
		{label: "6", width: 3, finger: Index, evCode: 7},
		{label: "7", width: 3, finger: Index, evCode: 8},
		{label: "8", width: 3, finger: Middle, evCode: 9},
		{label: "9", width: 3, finger: Ring, evCode: 10},
		{label: "0", width: 3, finger: Pinky, evCode: 11},
		{label: "-", width: 3, finger: Pinky, evCode: 12},
		{label: "=", width: 3, finger: Pinky, evCode: 13},
		{label: "<--", width: 8, finger: Pinky, evCode: 14},
		{label: "☼", width: 3, finger: Any, evCode: 111},
	},
	{
		{label: "Tab⇄", width: 6, finger: Pinky, evCode: 15},
		{label: "Q", width: 3, finger: Pinky, evCode: 16},
		{label: "W", width: 3, finger: Ring, evCode: 17},
		{label: "E", width: 3, finger: Middle, evCode: 18},
		{label: "R", width: 3, finger: Index, evCode: 19},
		{label: "T", width: 3, finger: Index, evCode: 20},
		{label: "Y", width: 3, finger: Index, evCode: 21},
		{label: "U", width: 3, finger: Index, evCode: 22},
		{label: "I", width: 3, finger: Middle, evCode: 23},
		{label: "O", width: 3, finger: Ring, evCode: 24},
		{label: "P", width: 3, finger: Pinky, evCode: 25},
		{label: "[", width: 3, finger: Pinky, evCode: 26},
		{label: "]", width: 3, finger: Pinky, evCode: 27},
		{label: "\\", width: 5, finger: Pinky, evCode: 43},
		{label: "⌂", width: 3, finger: Any, evCode: 102},
	},
	{
		{label: "Caps", width: 6, finger: Pinky, evCode: 58},
		{label: "A", width: 3, finger: Pinky, evCode: 30},
		{label: "S", width: 3, finger: Ring, evCode: 31},
		{label: "D", width: 3, finger: Middle, evCode: 32},
		{label: "F", width: 3, finger: Index, evCode: 33},
		{label: "G", width: 3, finger: Index, evCode: 34},
		{label: "H", width: 3, finger: Index, evCode: 35},
		{label: "J", width: 3, finger: Index, evCode: 36},
		{label: "K", width: 3, finger: Middle, evCode: 37},
		{label: "L", width: 3, finger: Ring, evCode: 38},
		{label: ";", width: 3, finger: Pinky, evCode: 39},
		{label: "'", width: 3, finger: Pinky, evCode: 40},
		{label: "Enter↵", width: 9, finger: Pinky, evCode: 28},
		{label: "⇡", width: 3, finger: Any, evCode: 104},
	},
	{
		{label: "Shift", width: 8, finger: Pinky, evCode: 42},
		{label: "Z", width: 3, finger: Pinky, evCode: 44},
		{label: "X", width: 3, finger: Ring, evCode: 45},
		{label: "C", width: 3, finger: Middle, evCode: 46},
		{label: "V", width: 3, finger: Index, evCode: 47},
		{label: "B", width: 3, finger: Index, evCode: 48},
		{label: "N", width: 3, finger: Index, evCode: 49},
		{label: "M", width: 3, finger: Index, evCode: 50},
		{label: ",", width: 3, finger: Middle, evCode: 51},
		{label: ".", width: 3, finger: Ring, evCode: 52},
		{label: "/", width: 3, finger: Pinky, evCode: 53},
		{label: "Shift", width: 7, finger: Pinky, evCode: 54},
		{label: "↑", width: 3, finger: Middle, evCode: 103},
		{label: "⇣", width: 3, finger: Any, evCode: 109},
	},
	{
		{label: "Ctrl", width: 6, finger: Pinky, evCode: 29},
		{label: "⌘", width: 3, finger: Ring, evCode: 125},
		{label: "Alt", width: 3, finger: Thumb, evCode: 56},
		{label: "Space", width: 22, finger: Thumb, evCode: 57},
		{label: "Alt", width: 3, finger: Thumb, evCode: 100},
		{label: "Fn", width: 3, finger: Ring, evCode: 127},
		{label: "Ctrl", width: 6, finger: Pinky, evCode: 97},
		{label: "←", width: 3, finger: Index, evCode: 105},
		{label: "↓", width: 3, finger: Middle, evCode: 108},
		{label: "→", width: 3, finger: Ring, evCode: 106},
	},
}

var size75 = [][]key{
	{
		{label: "Esc", width: 3, finger: Pinky, evCode: 1},
		{label: "F1", width: 3, finger: Pinky, evCode: 59},
		{label: "F2", width: 3, finger: Ring, evCode: 60},
		{label: "F3", width: 3, finger: Middle, evCode: 61},
		{label: "F4", width: 3, finger: Index, evCode: 62},
		{label: "F5", width: 3, finger: Index, evCode: 63},
		{label: "F6", width: 3, finger: Index, evCode: 64},
		{label: "F7", width: 3, finger: Index, evCode: 65},
		{label: "F8", width: 3, finger: Middle, evCode: 66},
		{label: "F9", width: 3, finger: Ring, evCode: 67},
		{label: "F10", width: 3, finger: Pinky, evCode: 68},
		{label: "F11", width: 3, finger: Pinky, evCode: 87},
		{label: "F12", width: 3, finger: Pinky, evCode: 88},
		{label: "Prt", width: 3, finger: Any, evCode: 99},
		{label: "Del", width: 4, finger: Any, evCode: 111},
		{label: "☼", width: 3, finger: Any, evCode: 119},
	},
	{
		{label: "`", width: 3, finger: Pinky, evCode: 41},
		{label: "1", width: 3, finger: Pinky, evCode: 2},
		{label: "2", width: 3, finger: Ring, evCode: 3},
		{label: "3", width: 3, finger: Middle, evCode: 4},
		{label: "4", width: 3, finger: Index, evCode: 5},
		{label: "5", width: 3, finger: Index, evCode: 6},
		{label: "6", width: 3, finger: Index, evCode: 7},
		{label: "7", width: 3, finger: Index, evCode: 8},
		{label: "8", width: 3, finger: Middle, evCode: 9},
		{label: "9", width: 3, finger: Ring, evCode: 10},
		{label: "0", width: 3, finger: Pinky, evCode: 11},
		{label: "-", width: 3, finger: Pinky, evCode: 12},
		{label: "=", width: 3, finger: Pinky, evCode: 13},
		{label: "<--", width: 8, finger: Pinky, evCode: 14},
		{label: "⇡", width: 3, finger: Any, evCode: 104},
	},
	{
		{label: "Tab⇄", width: 6, finger: Pinky, evCode: 15},
		{label: "Q", width: 3, finger: Pinky, evCode: 16},
		{label: "W", width: 3, finger: Ring, evCode: 17},
		{label: "E", width: 3, finger: Middle, evCode: 18},
		{label: "R", width: 3, finger: Index, evCode: 19},
		{label: "T", width: 3, finger: Index, evCode: 20},
		{label: "Y", width: 3, finger: Index, evCode: 21},
		{label: "U", width: 3, finger: Index, evCode: 22},
		{label: "I", width: 3, finger: Middle, evCode: 23},
		{label: "O", width: 3, finger: Ring, evCode: 24},
		{label: "P", width: 3, finger: Pinky, evCode: 25},
		{label: "[", width: 3, finger: Pinky, evCode: 26},
		{label: "]", width: 3, finger: Pinky, evCode: 27},
		{label: "\\", width: 5, finger: Pinky, evCode: 43},
		{label: "⇣", width: 3, finger: Any, evCode: 109},
	},
	{
		{label: "Caps", width: 6, finger: Pinky, evCode: 58},
		{label: "A", width: 3, finger: Pinky, evCode: 30},
		{label: "S", width: 3, finger: Ring, evCode: 31},
		{label: "D", width: 3, finger: Middle, evCode: 32},
		{label: "F", width: 3, finger: Index, evCode: 33},
		{label: "G", width: 3, finger: Index, evCode: 34},
		{label: "H", width: 3, finger: Index, evCode: 35},
		{label: "J", width: 3, finger: Index, evCode: 36},
		{label: "K", width: 3, finger: Middle, evCode: 37},
		{label: "L", width: 3, finger: Ring, evCode: 38},
		{label: ";", width: 3, finger: Pinky, evCode: 39},
		{label: "'", width: 3, finger: Pinky, evCode: 40},
		{label: "Enter↵", width: 9, finger: Pinky, evCode: 28},
		{label: "⌂", width: 3, finger: Any, evCode: 102},
	},
	{
		{label: "Shift", width: 8, finger: Pinky, evCode: 42},
		{label: "Z", width: 3, finger: Pinky, evCode: 44},
		{label: "X", width: 3, finger: Ring, evCode: 45},
		{label: "C", width: 3, finger: Middle, evCode: 46},
		{label: "V", width: 3, finger: Index, evCode: 47},
		{label: "B", width: 3, finger: Index, evCode: 48},
		{label: "N", width: 3, finger: Index, evCode: 49},
		{label: "M", width: 3, finger: Index, evCode: 50},
		{label: ",", width: 3, finger: Middle, evCode: 51},
		{label: ".", width: 3, finger: Ring, evCode: 52},
		{label: "/", width: 3, finger: Pinky, evCode: 53},
		{label: "Shift", width: 7, finger: Pinky, evCode: 54},
		{label: "↑", width: 3, finger: Middle, evCode: 103},
		{label: "⌿", width: 3, finger: Any, evCode: 107},
	},
	{
		{label: "Ctrl", width: 6, finger: Pinky, evCode: 29},
		{label: "⌘", width: 3, finger: Ring, evCode: 125},
		{label: "Alt", width: 3, finger: Thumb, evCode: 56},
		{label: "Space", width: 22, finger: Thumb, evCode: 57},
		{label: "Alt", width: 3, finger: Thumb, evCode: 100},
		{label: "Fn", width: 3, finger: Ring, evCode: 127},
		{label: "Ctrl", width: 6, finger: Pinky, evCode: 97},
		{label: "←", width: 3, finger: Index, evCode: 105},
		{label: "↓", width: 3, finger: Middle, evCode: 108},
		{label: "→", width: 3, finger: Ring, evCode: 106},
	},
}

var size80 = [][]key{
	{
		{label: "Esc", width: 3, finger: Pinky, evCode: 1},
		{label: "   ", width: 3, finger: Pinky, evCode: 0},
		{label: "F1", width: 3, finger: Pinky, evCode: 59},
		{label: "F2", width: 3, finger: Ring, evCode: 60},
		{label: "F3", width: 3, finger: Middle, evCode: 61},
		{label: "F4", width: 3, finger: Index, evCode: 62},
		{label: "  ", width: 2, finger: Index, evCode: 0},
		{label: "F5", width: 3, finger: Index, evCode: 63},
		{label: "F6", width: 3, finger: Index, evCode: 64},
		{label: "F7", width: 3, finger: Index, evCode: 65},
		{label: "F8", width: 3, finger: Middle, evCode: 66},
		{label: "  ", width: 2, finger: Index, evCode: 0},
		{label: "F9", width: 3, finger: Ring, evCode: 67},
		{label: "F10", width: 3, finger: Pinky, evCode: 68},
		{label: "F11", width: 3, finger: Pinky, evCode: 87},
		{label: "F12", width: 3, finger: Pinky, evCode: 88},
		{label: "  ", width: 2, finger: Index, gap: true, evCode: 0},
		{label: "Prt", width: 3, finger: Index, evCode: 99},
		{label: "⚲", width: 3, finger: Middle, evCode: 70},
		{label: "☼", width: 3, finger: Ring, evCode: 119},
	},
	{
		{label: "`", width: 3, finger: Pinky, evCode: 41},
		{label: "1", width: 3, finger: Pinky, evCode: 2},
		{label: "2", width: 3, finger: Ring, evCode: 3},
		{label: "3", width: 3, finger: Middle, evCode: 4},
		{label: "4", width: 3, finger: Index, evCode: 5},
		{label: "5", width: 3, finger: Index, evCode: 6},
		{label: "6", width: 3, finger: Index, evCode: 7},
		{label: "7", width: 3, finger: Index, evCode: 8},
		{label: "8", width: 3, finger: Middle, evCode: 9},
		{label: "9", width: 3, finger: Ring, evCode: 10},
		{label: "0", width: 3, finger: Pinky, evCode: 11},
		{label: "-", width: 3, finger: Pinky, evCode: 12},
		{label: "=", width: 3, finger: Pinky, evCode: 13},
		{label: "<--", width: 9, finger: Pinky, evCode: 14},
		{label: "  ", width: 2, finger: Pinky, gap: true, evCode: 0},
		{label: "Ins", width: 3, finger: Index, evCode: 110},
		{label: "⌂", width: 3, finger: Middle, evCode: 102},
		{label: "⇡", width: 3, finger: Ring, evCode: 104},
	},
	{
		{label: "Tab⇄", width: 7, finger: Pinky, evCode: 15},
		{label: "Q", width: 3, finger: Pinky, evCode: 16},
		{label: "W", width: 3, finger: Ring, evCode: 17},
		{label: "E", width: 3, finger: Middle, evCode: 18},
		{label: "R", width: 3, finger: Index, evCode: 19},
		{label: "T", width: 3, finger: Index, evCode: 20},
		{label: "Y", width: 3, finger: Index, evCode: 21},
		{label: "U", width: 3, finger: Index, evCode: 22},
		{label: "I", width: 3, finger: Middle, evCode: 23},
		{label: "O", width: 3, finger: Ring, evCode: 24},
		{label: "P", width: 3, finger: Pinky, evCode: 25},
		{label: "[", width: 3, finger: Pinky, evCode: 26},
		{label: "]", width: 3, finger: Pinky, evCode: 27},
		{label: "\\", width: 5, finger: Pinky, evCode: 43},
		{label: "  ", width: 2, finger: Pinky, gap: true, evCode: 0},
		{label: "Del", width: 3, finger: Index, evCode: 111},
		{label: "⌿", width: 3, finger: Middle, evCode: 107},
		{label: "⇣", width: 3, finger: Ring, evCode: 109},
	},
	{
		{label: "Caps", width: 6, finger: Pinky, evCode: 58},
		{label: "A", width: 3, finger: Pinky, evCode: 30},
		{label: "S", width: 3, finger: Ring, evCode: 31},
		{label: "D", width: 3, finger: Middle, evCode: 32},
		{label: "F", width: 3, finger: Index, evCode: 33},
		{label: "G", width: 3, finger: Index, evCode: 34},
		{label: "H", width: 3, finger: Index, evCode: 35},
		{label: "J", width: 3, finger: Index, evCode: 36},
		{label: "K", width: 3, finger: Middle, evCode: 37},
		{label: "L", width: 3, finger: Ring, evCode: 38},
		{label: ";", width: 3, finger: Pinky, evCode: 39},
		{label: "'", width: 3, finger: Pinky, evCode: 40},
		{label: "Enter↵", width: 10, finger: Pinky, evCode: 28},
		{label: "      ", width: 6, finger: Pinky, gap: true, rightless: true, leftless: false, evCode: 0},
		{label: "   ", width: 3, finger: Pinky, gap: false, rightless: true, leftless: true, evCode: 0},
		{label: "   ", width: 3, finger: Pinky, gap: true, rightless: false, leftless: false, evCode: 0},
	},
	{
		{label: "Shift", width: 11, finger: Pinky, evCode: 42},
		{label: "Z", width: 3, finger: Pinky, evCode: 44},
		{label: "X", width: 3, finger: Ring, evCode: 45},
		{label: "C", width: 3, finger: Middle, evCode: 46},
		{label: "V", width: 3, finger: Index, evCode: 47},
		{label: "B", width: 3, finger: Index, evCode: 48},
		{label: "N", width: 3, finger: Index, evCode: 49},
		{label: "M", width: 3, finger: Index, evCode: 50},
		{label: ",", width: 3, finger: Middle, evCode: 51},
		{label: ".", width: 3, finger: Ring, evCode: 52},
		{label: "/", width: 3, finger: Pinky, evCode: 53},
		{label: "Shift", width: 9, finger: Pinky, evCode: 54},
		{label: "  ", width: 2, finger: Pinky, gap: true, rightless: true, leftless: false, evCode: 0},
		{label: "   ", width: 3, finger: Pinky, evCode: 0},
		{label: "↑", width: 3, finger: Middle, evCode: 103},
		{label: "   ", width: 3, finger: Pinky, evCode: 0},
	},
	{
		{label: "Ctrl", width: 6, finger: Pinky, evCode: 29},
		{label: "⌘", width: 3, finger: Ring, evCode: 125},
		{label: "Alt", width: 5, finger: Thumb, evCode: 56},
		{label: "Space", width: 23, finger: Thumb, evCode: 57},
		{label: "Alt", width: 5, finger: Thumb, evCode: 100},
		{label: "⌘", width: 3, finger: Ring, evCode: 126},
		{label: "Fn", width: 3, finger: Ring, evCode: 127},
		{label: "Ctrl", width: 6, finger: Pinky, evCode: 97},
		{label: "  ", width: 2, finger: Pinky, evCode: 0},
		{label: "←", width: 3, finger: Index, evCode: 105},
		{label: "↓", width: 3, finger: Middle, evCode: 108},
		{label: "→", width: 3, finger: Ring, evCode: 106},
	},
}

var size96 = [][]key{
	{
		{label: "Esc", width: 3, finger: Pinky, evCode: 1},
		{label: "F1", width: 3, finger: Pinky, evCode: 59},
		{label: "F2", width: 3, finger: Ring, evCode: 60},
		{label: "F3", width: 3, finger: Middle, evCode: 61},
		{label: "F4", width: 3, finger: Index, evCode: 62},
		{label: "F5", width: 3, finger: Index, evCode: 63},
		{label: "F6", width: 3, finger: Index, evCode: 64},
		{label: "F7", width: 3, finger: Index, evCode: 65},
		{label: "F8", width: 3, finger: Middle, evCode: 66},
		{label: "F9", width: 3, finger: Ring, evCode: 67},
		{label: "F10", width: 3, finger: Pinky, evCode: 68},
		{label: "F11", width: 3, finger: Pinky, evCode: 87},
		{label: "F12", width: 3, finger: Pinky, evCode: 88},
		{label: "Del", width: 3, finger: Any, evCode: 111},
		{label: "⌂", width: 3, finger: Any, evCode: 102},
		{label: "⌿", width: 3, finger: Any, evCode: 107},
		{label: "⇡", width: 3, finger: Any, evCode: 104},
		{label: "⇣", width: 3, finger: Any, evCode: 109},
		{label: "☼", width: 3, finger: Any, evCode: 119},
	},
	{
		{label: "`", width: 3, finger: Pinky, evCode: 41},
		{label: "1", width: 3, finger: Pinky, evCode: 2},
		{label: "2", width: 3, finger: Ring, evCode: 3},
		{label: "3", width: 3, finger: Middle, evCode: 4},
		{label: "4", width: 3, finger: Index, evCode: 5},
		{label: "5", width: 3, finger: Index, evCode: 6},
		{label: "6", width: 3, finger: Index, evCode: 7},
		{label: "7", width: 3, finger: Index, evCode: 8},
		{label: "8", width: 3, finger: Middle, evCode: 9},
		{label: "9", width: 3, finger: Ring, evCode: 10},
		{label: "0", width: 3, finger: Pinky, evCode: 11},
		{label: "-", width: 3, finger: Pinky, evCode: 12},
		{label: "=", width: 3, finger: Pinky, evCode: 13},
		{label: "<--", width: 7, finger: Pinky, evCode: 14},
		{label: "Nlk", width: 3, finger: Index, evCode: 69},
		{label: "/", width: 3, finger: Middle, evCode: 98},
		{label: "*", width: 3, finger: Ring, evCode: 55},
		{label: "-", width: 3, finger: Pinky, evCode: 74},
	},
	{
		{label: "Tab ⇄", width: 7, finger: Pinky, evCode: 15},
		{label: "Q", width: 3, finger: Pinky, evCode: 16},
		{label: "W", width: 3, finger: Ring, evCode: 17},
		{label: "E", width: 3, finger: Middle, evCode: 18},
		{label: "R", width: 3, finger: Index, evCode: 19},
		{label: "T", width: 3, finger: Index, evCode: 20},
		{label: "Y", width: 3, finger: Index, evCode: 21},
		{label: "U", width: 3, finger: Index, evCode: 22},
		{label: "I", width: 3, finger: Middle, evCode: 23},
		{label: "O", width: 3, finger: Ring, evCode: 24},
		{label: "P", width: 3, finger: Pinky, evCode: 25},
		{label: "[", width: 3, finger: Pinky, evCode: 26},
		{label: "]", width: 3, finger: Pinky, evCode: 27},
		{label: "\\", width: 3, finger: Pinky, evCode: 43},
		{label: "7", width: 3, finger: Index, evCode: 71},
		{label: "8", width: 3, finger: Middle, evCode: 72},
		{label: "9", width: 3, finger: Ring, evCode: 73},
		{label: "   ", width: 3, finger: Pinky, gap: true, divLabel: "+", evCode: 78},
	},
	{
		{label: "Caps", width: 6, finger: Pinky, evCode: 58},
		{label: "A", width: 3, finger: Pinky, evCode: 30},
		{label: "S", width: 3, finger: Ring, evCode: 31},
		{label: "D", width: 3, finger: Middle, evCode: 32},
		{label: "F", width: 3, finger: Index, evCode: 33},
		{label: "G", width: 3, finger: Index, evCode: 34},
		{label: "H", width: 3, finger: Index, evCode: 35},
		{label: "J", width: 3, finger: Index, evCode: 36},
		{label: "K", width: 3, finger: Middle, evCode: 37},
		{label: "L", width: 3, finger: Ring, evCode: 38},
		{label: ";", width: 3, finger: Pinky, evCode: 39},
		{label: "'", width: 3, finger: Pinky, evCode: 40},
		{label: "Enter↵", width: 8, finger: Pinky, evCode: 28},
		{label: "4", width: 3, finger: Index, evCode: 75},
		{label: "5", width: 3, finger: Middle, evCode: 76},
		{label: "6", width: 3, finger: Ring, evCode: 77},
		{label: "   ", width: 3, finger: Pinky, evCode: 0},
	},
	{
		{label: "Shift", width: 7, finger: Pinky, evCode: 42},
		{label: "Z", width: 3, finger: Pinky, evCode: 44},
		{label: "X", width: 3, finger: Ring, evCode: 45},
		{label: "C", width: 3, finger: Middle, evCode: 46},
		{label: "V", width: 3, finger: Index, evCode: 47},
		{label: "B", width: 3, finger: Index, evCode: 48},
		{label: "N", width: 3, finger: Index, evCode: 49},
		{label: "M", width: 3, finger: Index, evCode: 50},
		{label: ",", width: 3, finger: Middle, evCode: 51},
		{label: ".", width: 3, finger: Ring, evCode: 52},
		{label: "/", width: 3, finger: Pinky, evCode: 53},
		{label: "Shift", width: 7, finger: Pinky, evCode: 54},
		{label: "↑", width: 3, finger: Middle, evCode: 103},
		{label: "1", width: 3, finger: Index, evCode: 79},
		{label: "2", width: 3, finger: Middle, evCode: 80},
		{label: "3", width: 3, finger: Ring, evCode: 81},
		{label: "   ", width: 3, finger: Pinky, gap: true, divLabel: "↵", evCode: 96},
	},
	{
		{label: "Ctrl", width: 6, finger: Pinky, evCode: 29},
		{label: "⌘", width: 3, finger: Ring, evCode: 125},
		{label: "Alt", width: 5, finger: Thumb, evCode: 56},
		{label: "Space", width: 17, finger: Thumb, evCode: 57},
		{label: "Alt", width: 5, finger: Thumb, evCode: 100},
		{label: "Fn", width: 3, finger: Ring, evCode: 127},
		{label: "Ctrl", width: 6, finger: Pinky, evCode: 97},
		{label: "←", width: 3, finger: Index, evCode: 105},
		{label: "↓", width: 3, finger: Middle, evCode: 108},
		{label: "→", width: 3, finger: Ring, evCode: 106},
		{label: "0", width: 3, finger: Middle, evCode: 82},
		{label: ".", width: 3, finger: Ring, evCode: 83},
		{label: "   ", width: 3, finger: Pinky, evCode: 0},
	},
}

var size100 = [][]key{
	{
		{label: "Esc", width: 3, finger: Pinky, evCode: 1},
		{label: "   ", width: 3, finger: Pinky, evCode: 0},
		{label: "F1", width: 3, finger: Pinky, evCode: 59},
		{label: "F2", width: 3, finger: Ring, evCode: 60},
		{label: "F3", width: 3, finger: Middle, evCode: 61},
		{label: "F4", width: 3, finger: Index, evCode: 62},
		{label: "  ", width: 2, finger: Index, evCode: 0},
		{label: "F5", width: 3, finger: Index, evCode: 63},
		{label: "F6", width: 3, finger: Index, evCode: 64},
		{label: "F7", width: 3, finger: Index, evCode: 65},
		{label: "F8", width: 3, finger: Middle, evCode: 66},
		{label: "  ", width: 2, finger: Index, evCode: 0},
		{label: "F9", width: 3, finger: Ring, evCode: 67},
		{label: "F10", width: 3, finger: Pinky, evCode: 68},
		{label: "F11", width: 3, finger: Pinky, evCode: 87},
		{label: "F12", width: 3, finger: Pinky, evCode: 88},
		{label: "  ", width: 2, finger: Index, gap: true, evCode: 0},
		{label: "Prt", width: 3, finger: Index, evCode: 99},
		{label: "⚲", width: 3, finger: Middle, evCode: 70},
		{label: "☼", width: 3, finger: Ring, evCode: 119},
		{label: " ", width: 2, finger: Index, gap: true, rightless: true, evCode: 0},
		{label: " ", width: 3, finger: Index, rightless: true, leftless: true, evCode: 0},
		{label: " ", width: 3, finger: Index, rightless: true, leftless: true, evCode: 0},
		{label: " ", width: 3, finger: Index, rightless: true, leftless: true, evCode: 0},
		{label: " ", width: 3, finger: Index, evCode: 0},
	},
	{
		{label: "`", width: 3, finger: Pinky, evCode: 41},
		{label: "1", width: 3, finger: Pinky, evCode: 2},
		{label: "2", width: 3, finger: Ring, evCode: 3},
		{label: "3", width: 3, finger: Middle, evCode: 4},
		{label: "4", width: 3, finger: Index, evCode: 5},
		{label: "5", width: 3, finger: Index, evCode: 6},
		{label: "6", width: 3, finger: Index, evCode: 7},
		{label: "7", width: 3, finger: Index, evCode: 8},
		{label: "8", width: 3, finger: Middle, evCode: 9},
		{label: "9", width: 3, finger: Ring, evCode: 10},
		{label: "0", width: 3, finger: Pinky, evCode: 11},
		{label: "-", width: 3, finger: Pinky, evCode: 12},
		{label: "=", width: 3, finger: Pinky, evCode: 13},
		{label: "<--", width: 9, finger: Pinky, evCode: 14},
		{label: "  ", width: 2, finger: Pinky, gap: true, evCode: 0},
		{label: "Ins", width: 3, finger: Index, evCode: 110},
		{label: "⌂", width: 3, finger: Middle, evCode: 102},
		{label: "⇡", width: 3, finger: Ring, evCode: 104},
		{label: "  ", width: 2, finger: Pinky, gap: true, evCode: 0},
		{label: "Nlk", width: 3, finger: Index, evCode: 69},
		{label: "/", width: 3, finger: Middle, evCode: 98},
		{label: "*", width: 3, finger: Ring, evCode: 55},
		{label: "-", width: 3, finger: Pinky, evCode: 74},
	},
	{
		{label: "Tab ⇄", width: 7, finger: Pinky, evCode: 15},
		{label: "Q", width: 3, finger: Pinky, evCode: 16},
		{label: "W", width: 3, finger: Ring, evCode: 17},
		{label: "E", width: 3, finger: Middle, evCode: 18},
		{label: "R", width: 3, finger: Index, evCode: 19},
		{label: "T", width: 3, finger: Index, evCode: 20},
		{label: "Y", width: 3, finger: Index, evCode: 21},
		{label: "U", width: 3, finger: Index, evCode: 22},
		{label: "I", width: 3, finger: Middle, evCode: 23},
		{label: "O", width: 3, finger: Ring, evCode: 24},
		{label: "P", width: 3, finger: Pinky, evCode: 25},
		{label: "[", width: 3, finger: Pinky, evCode: 26},
		{label: "]", width: 3, finger: Pinky, evCode: 27},
		{label: "\\", width: 5, finger: Pinky, evCode: 43},
		{label: "  ", width: 2, finger: Pinky, gap: true, evCode: 0},
		{label: "Del", width: 3, finger: Index, evCode: 111},
		{label: "⌿", width: 3, finger: Middle, evCode: 107},
		{label: "⇣", width: 3, finger: Ring, evCode: 109},
		{label: "  ", width: 2, finger: Pinky, gap: true, evCode: 0},
		{label: "7", width: 3, finger: Index, evCode: 71},
		{label: "8", width: 3, finger: Middle, evCode: 72},
		{label: "9", width: 3, finger: Ring, evCode: 73},
		{label: "   ", width: 3, finger: Pinky, gap: true, divLabel: "+", evCode: 78},
	},
	{
		{label: "Caps", width: 6, finger: Pinky, evCode: 58},
		{label: "A", width: 3, finger: Pinky, evCode: 30},
		{label: "S", width: 3, finger: Ring, evCode: 31},
		{label: "D", width: 3, finger: Middle, evCode: 32},
		{label: "F", width: 3, finger: Index, evCode: 33},
		{label: "G", width: 3, finger: Index, evCode: 34},
		{label: "H", width: 3, finger: Index, evCode: 35},
		{label: "J", width: 3, finger: Index, evCode: 36},
		{label: "K", width: 3, finger: Middle, evCode: 37},
		{label: "L", width: 3, finger: Ring, evCode: 38},
		{label: ";", width: 3, finger: Pinky, evCode: 39},
		{label: "'", width: 3, finger: Pinky, evCode: 40},
		{label: "Enter↵", width: 10, finger: Pinky, evCode: 28},
		{label: " ", width: 6, finger: Pinky, gap: true, rightless: true, leftless: false, evCode: 0},
		{label: " ", width: 3, finger: Pinky, gap: false, rightless: true, leftless: true, evCode: 0},
		{label: " ", width: 6, finger: Pinky, gap: true, rightless: false, leftless: false, evCode: 0},
		{label: "4", width: 3, finger: Index, evCode: 75},
		{label: "5", width: 3, finger: Middle, evCode: 76},
		{label: "6", width: 3, finger: Ring, evCode: 77},
		{label: "   ", width: 3, finger: Pinky, evCode: 0},
	},
	{
		{label: "Shift", width: 11, finger: Pinky, evCode: 42},
		{label: "Z", width: 3, finger: Pinky, evCode: 44},
		{label: "X", width: 3, finger: Ring, evCode: 45},
		{label: "C", width: 3, finger: Middle, evCode: 46},
		{label: "V", width: 3, finger: Index, evCode: 47},
		{label: "B", width: 3, finger: Index, evCode: 48},
		{label: "N", width: 3, finger: Index, evCode: 49},
		{label: "M", width: 3, finger: Index, evCode: 50},
		{label: ",", width: 3, finger: Middle, evCode: 51},
		{label: ".", width: 3, finger: Ring, evCode: 52},
		{label: "/", width: 3, finger: Pinky, evCode: 53},
		{label: "Shift", width: 9, finger: Pinky, evCode: 54},
		{label: " ", width: 2, finger: Pinky, gap: true, rightless: true, leftless: false, evCode: 0},
		{label: " ", width: 3, finger: Pinky, evCode: 0},
		{label: "↑", width: 3, finger: Middle, evCode: 103},
		{label: " ", width: 3, finger: Pinky, rightless: true, leftless: true, evCode: 0},
		{label: " ", width: 2, finger: Pinky, gap: true, evCode: 0},
		{label: "1", width: 3, finger: Index, evCode: 79},
		{label: "2", width: 3, finger: Middle, evCode: 80},
		{label: "3", width: 3, finger: Ring, evCode: 81},
		{label: " ", width: 3, finger: Pinky, gap: true, divLabel: "↵", evCode: 96},
	},
	{
		{label: "Ctrl", width: 6, finger: Pinky, evCode: 29},
		{label: "⌘", width: 3, finger: Ring, evCode: 125},
		{label: "Alt", width: 5, finger: Thumb, evCode: 56},
		{label: "Space", width: 23, finger: Thumb, evCode: 57},
		{label: "Alt", width: 5, finger: Thumb, evCode: 100},
		{label: "⌘", width: 3, finger: Ring, evCode: 126},
		{label: "Fn", width: 3, finger: Ring, evCode: 127},
		{label: "Ctrl", width: 6, finger: Pinky, evCode: 97},
		{label: "  ", width: 2, finger: Pinky, evCode: 0},
		{label: "←", width: 3, finger: Index, evCode: 105},
		{label: "↓", width: 3, finger: Middle, evCode: 108},
		{label: "→", width: 3, finger: Ring, evCode: 106},
		{label: "  ", width: 2, finger: Pinky, gap: true, evCode: 0},
		{label: "0", width: 7, finger: Thumb, evCode: 82},
		{label: ".", width: 3, finger: Ring, evCode: 83},
		{label: "   ", width: 3, finger: Pinky, evCode: 0},
	},
}
